# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"+\n\x0b\x44\x61teBooking\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\":\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x1b\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x0c.DateBooking\"A\n\x0f\x42ookingFeedback\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1d\n\x07\x62ooking\x18\x02 \x01(\x0b\x32\x0c.BookingData\";\n\nOneBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t\"\x18\n\x06UserId\x12\x0e\n\x06userid\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyBooking2\xa7\x01\n\x07\x42ooking\x12\x32\n\x0fGetListBookings\x12\r.EmptyBooking\x1a\x0c.BookingData\"\x00\x30\x01\x12\x31\n\x12GetBookingByUserId\x12\x07.UserId\x1a\x10.BookingFeedback\"\x00\x12\x35\n\x12\x41\x64\x64\x42ookingByUserId\x12\x0b.OneBooking\x1a\x10.BookingFeedback\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATEBOOKING._serialized_start=17
  _DATEBOOKING._serialized_end=60
  _BOOKINGDATA._serialized_start=62
  _BOOKINGDATA._serialized_end=120
  _BOOKINGFEEDBACK._serialized_start=122
  _BOOKINGFEEDBACK._serialized_end=187
  _ONEBOOKING._serialized_start=189
  _ONEBOOKING._serialized_end=248
  _USERID._serialized_start=250
  _USERID._serialized_end=274
  _EMPTYBOOKING._serialized_start=276
  _EMPTYBOOKING._serialized_end=290
  _BOOKING._serialized_start=293
  _BOOKING._serialized_end=460
# @@protoc_insertion_point(module_scope)
